INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Salário', '+');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Aluguel', '+');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Horas extras', '+');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, '13º salário', '+');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Férias', '+');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Outros', '+');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Aluguel', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Condomínio', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Gás', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'IPTU', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Manutenção Casa', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Prestação do carro', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Seguro do carro', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Estacionamento', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'IPVA', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Combustível', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Manutenção Carro', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Outros Transportes', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Plano de saúde', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Medicamentos', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Médico / Hospital', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Destista', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Colégio', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Faculdade', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Curso', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Material escolar', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Uniforme', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Luz', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Água', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Telefone Fixo', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Celular', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Mensalidade TV', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Mensalidade Internet', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Supermercado', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Padara, Restaurante, etc', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Beleza e Estética', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Academia e Clube', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Animais de Estimação', '-');
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Parcelas Empréstimos', '-');v
INSERT INTO Categoria (ID, Nome, Tipo) VALUES (NULL, 'Diversos', '-');
